DAY-10 / 8-FEB 2026

In [2]:
#ADVANCE INDEXING
import numpy as np
x=np.array([[1,2],[3,4],[5,6]])
y=x[[0,1,2],[0,1,0]]
print(y)

[1 4 5]


In [3]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
#print(x)
z=x[1:4,1:3]     # USING SLICING
print(z)
y=x[1:4,[1,2]]   # USING ADVANCE INDEXING
print(y)

[[ 4  5]
 [ 7  8]
 [10 11]]
[[ 4  5]
 [ 7  8]
 [10 11]]


In [4]:
# DISPLAY ELEMENTS GREATER THAN FIVE

x=np.array([[0,1,2],[13,4,5],[6,7,8],[9,10,11]])
print('the items greater than 5 are:')
print(x[x>5])

the items greater than 5 are:
[13  6  7  8  9 10 11]


In [5]:
#assigning
arr=np.array([2,4,6,8,10])
nc=arr
nc[0]=12
print('original array:',arr)
print('assigned array:',nc)

original array: [12  4  6  8 10]
assigned array: [12  4  6  8 10]
