DAY-2 / 31-JAN 2026

In [ ]:
# linspace()                                                       

import numpy as np
a=np.linspace(1,10,5) # will get 5 values between 1 to 10 which will be evenly distributed
print(a)
b=np.linspace(1,10)
print(b)

[ 1.    3.25  5.5   7.75 10.  ]
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [5]:
# zeros()

a=np.zeros(5) # to get the dersied amount of zeros
print(a)
b=np.zeros([3,4])
print(b)
c=np.zeros((2,2))
print(c)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]]


In [ ]:
# ones()

a=np.ones(4)
print(a)
b=np.ones([2,3])
print(b)
c=np.ones((2,2,2))
print(c)

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [ ]:
# eye()

a=np.eye(5) #(unit matrics)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# empty()

a=np.empty(7)    #random values
print(a)

[3.47739925e-081 2.75117553e+180 1.57313211e-076 7.50128528e-067
 1.27118689e-075 1.05699581e-307 3.58423917e+246]


In [ ]:
# arange()

a=np.arange(3)  #random value bydefault starting from 0 till the (given value-1)
print(a)
b=np.arange(1,7)   #random value starting from desired value till the (given value-1)
print(b)

[0 1 2]
[1 2 3 4 5 6]


In [20]:
# even number between 1-10

a=np.arange(2,10,2)
print(a)

[2 4 6 8]


In [24]:
# logspace()

print("B\n",np.logspace(2.0,3.0,num=5, base=11)) #BASE=11
print("B\n",np.logspace(2.0,3.0,num=5)) #BASE=10
print("B\n",np.logspace(2.0,3.0,num=5, dtype = int)) #BASE=10

B
 [ 121.          220.36039471  401.31159963  730.8527479  1331.        ]
B
 [ 100.          177.827941    316.22776602  562.34132519 1000.        ]
B
 [ 100  177  316  562 1000]
