DAY-6 / 04-FEB 2026

In [1]:
# ATTRIBUTE ndim,shape                                                                                              # 3-FEB 2026
# ndim - find out no. of dimension of an array    
# shape -   to find out the                                                                 
import numpy as np
arr=np.array([[1,2,3,4]])
print(arr.ndim)
print(arr.shape)             

# ndmin - add desired no. of dimension to the array
arr=np.array([1,2,3,4],ndmin=4)
print(arr)
print(arr.ndim)
print(arr.shape)

arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

2
(1, 4)
[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)
(2, 4)


In [2]:
# ATTRIBUTE - reshape
import numpy as np 
arr=np.array([[1,2,3],[4,5,6]]) # since its a (2,3) all the possible multiplication is - reshape can be done and also (1,1,6) is also possible
print(arr)
print(arr.reshape(1,6))  
print(arr.ndim)

b=arr.reshape(1,1,6)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
2
[[[1 2 3 4 5 6]]]


In [3]:
print(arr.size)     # SIZE  - no. of elements
print(arr.itemsize)  # itemsize -size of one element
print(arr.nbytes)  #  nbytes - total size of elements

6
8
48


In [4]:
a=np.arange(24)
print(a.ndim)

b=a.reshape(2,4,3)
print(b)

1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
