DAY-11 / 10-feb 2026

In [1]:
#using copy function
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [2]:
#view
x=arr.view()
arr[0]=24
print(arr)
print(x)

[24  2  3  4  5]
[24  2  3  4  5]
