In [1]:
#dtype
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

arr=np.array([1,2,3,4.0])
print(arr.dtype)
print(arr)

int64
<U6
float64
[1. 2. 3. 4.]


In [2]:
#creating array with defined data type
arr=np.array([1,2,3,4],dtype='i4')  
print(arr.dtype)
print(arr)

arr=np.array([1,2,3,4],dtype='i2')  
print(arr.dtype)
print(arr)

arr=np.array([1,2,3,4],dtype='i1')  
print(arr.dtype)
print(arr)

arr=np.array([1,2,3,4],dtype='i3')  #error
print(arr.dtype)
print(arr)

int32
[1 2 3 4]
int16
[1 2 3 4]
int8
[1 2 3 4]


TypeError: data type 'i3' not understood

In [3]:
#converting data type on existing arrays
arr=np.array([1.1,2.1,3.1,4.1])
print(arr)
print(arr.dtype)

new=arr.astype('i')
print(new)
print(new.dtype)

[1.1 2.1 3.1 4.1]
float64
[1 2 3 4]
int32


In [4]:
arr=np.array([1,0,3])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool
