In [1]:
#NUMPY ARRAY ITERATING 
import numpy as np                                             #7-FEB 2026
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [2]:
arr=np.array([[1,2,3],[4,5,6]])          # in this 2d array is considered as 1d array 
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [3]:
arr=np.array([[1,2,3],[4,5,6]])          
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [4]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])          
for x in arr:
    for y in x:
        #for z in y:
            print("x represents the 2D array:")
            print(x)

x represents the 2D array:
[[1 2 3]
 [4 5 6]]
x represents the 2D array:
[[1 2 3]
 [4 5 6]]
x represents the 2D array:
[[ 7  8  9]
 [10 11 12]]
x represents the 2D array:
[[ 7  8  9]
 [10 11 12]]


In [5]:
#iterating arrays using nditer()

arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [6]:
#iterating with different step size

arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7
