In [1]:
#operations on numpy array  
# array with array                                                                                            # 2-FEB 2026
import numpy as np
a=np.arange(0,6)
print(a)
print(a+a)
print(a-a)
print(a*a)
print(a/a)

[0 1 2 3 4 5]
[ 0  2  4  6  8 10]
[0 0 0 0 0 0]
[ 0  1  4  9 16 25]
[nan  1.  1.  1.  1.  1.]


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12464\2418661174.py:9: RuntimeWarning: invalid value encountered in divide
  print(a/a)


In [2]:
# array with scalar
print(a-100)
print(1/a)
print(a**2)

[-100  -99  -98  -97  -96  -95]
[       inf 1.         0.5        0.33333333 0.25       0.2       ]
[ 0  1  4  9 16 25]


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12464\259672271.py:3: RuntimeWarning: divide by zero encountered in divide
  print(1/a)
