DAY-3 / 1-FEB 2026

In [2]:
# 1.random.rand()
import numpy as np
a=np.random.rand(3)
print(a)
b=np.random.rand(2,2)
print(b)
c=np.random.rand(2,3,4)
print(c)

[0.24075048 0.27682771 0.51363114]
[[0.21973467 0.558871  ]
 [0.77034617 0.87269624]]
[[[0.20217845 0.97172088 0.52008223 0.15503098]
  [0.80690102 0.73942619 0.03546965 0.99472283]
  [0.09555782 0.57104765 0.52278873 0.35872262]]

 [[0.26526718 0.79225793 0.17164666 0.55857519]
  [0.76809117 0.23801582 0.25028756 0.88932474]
  [0.25436897 0.81765313 0.65235112 0.31485884]]]


In [4]:
# 2.random.randint()
import numpy as np
a=np.random.randint(4)  # any one value between 0 to given value -1
print(a)
b=np.random.randint(1,10,5)   #any 5 value starting from desired value to given value -1
print(b)

1
[3 7 4 3 7]


In [5]:
# want +ve random numbers
a=np.random.randint(1,10,[2,3])
print(a)
b=np.random.randint(1,10,[2,2,2])
print(b)
c=np.random.randint((3,3,3))
print(c)

[[6 8 1]
 [7 3 6]]
[[[8 1]
  [9 1]]

 [[7 6]
  [6 5]]]
[0 0 2]
