DAY-8 / 6-FEB 2026

In [4]:
#2D slicing                                        # 5-FEB 2026
import numpy as np                                                  
a=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print(a[1:])

b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b[1,1:4])
print(b[1:4])
print(b[:,1:4])
print(b[:,:4])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[3 4 5]
 [4 5 6]]
[7 8 9]
[[ 6  7  8  9 10]]
[[2 3 4]
 [7 8 9]]
[[1 2 3 4]
 [6 7 8 9]]


In [5]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b[0:2,2])
c=b[0:2,2]
print(c.shape)
print(c.ndim)
#print(b[0:2,2:4])

[3 8]
(2,)
1


In [6]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2:2,1:4:2])
print(arr[0:2,1:4])

[[2 4]]
[[2 3 4]
 [7 8 9]]
