DAY-6 / 04-FEB 2026

In [1]:
# ATTRIBUTE ndim,shape                                                                                              # 3-FEB 2026
# ndim - find out no. of dimension of an array    
# shape -   to find out the                                                                 
import numpy as np
arr=np.array([[1,2,3,4]])
print(arr.ndim)
print(arr.shape)             

# ndmin - add desired no. of dimension to the array
arr=np.array([1,2,3,4],ndmin=4)
print(arr)
print(arr.ndim)
print(arr.shape)

arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

2
(1, 4)
[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)
(2, 4)


In [2]:
# ATTRIBUTE - reshape
import numpy as np 
arr=np.array([[1,2,3],[4,5,6]]) # since its a (2,3) all the possible multiplication is - reshape can be done and also (1,1,6) is also possible
print(arr)
print(arr.reshape(1,6))  
print(arr.ndim)

b=arr.reshape(1,1,6)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
2
[[[1 2 3 4 5 6]]]


In [3]:
print(arr.size)     # SIZE  - no. of elements
print(arr.itemsize)  # itemsize -size of one element
print(arr.nbytes)  #  nbytes - total size of elements

6
8
48


In [4]:
a=np.arange(24)
print(a.ndim)

b=a.reshape(2,4,3)
print(b)

1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [5]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2)
print(a)
print(b)
c=a.reshape(-1) # or c=a.reshape(6,)
print(c)
print(c.shape)
print(c.ndim)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
(6,)
1


In [6]:
#flatten() - to convert it in one dimension 
a=np.array([[1,4,7],[12,5,8],[3,6,9]])
b=a.flatten() #(it gives row wise output)
print(b)

c=a.flatten('F') #(it gives column wise output)
print(c)

[ 1  4  7 12  5  8  3  6  9]
[ 1 12  3  4  5  6  7  8  9]


In [7]:
# INDEXING AND SLICING 
a=np.arange(10)
print(a)
b=a[2:7:2]
print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [8]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[3])
print(arr[2:5])
print(arr[::2])
print(arr[2:])
print(arr[:2])
print(arr[4::4])
print(arr[1:1:1])

4
[3 4 5]
[1 3 5 7]
[3 4 5 6 7]
[1 2]
[5]
[]


In [9]:
print(arr[-3:-1])
print(arr[::-1])
print(arr[-1:-3])

[5 6]
[7 6 5 4 3 2 1]
[]
