1.IMPORT NUMPY
2.SLICING

In [ ]:
import numpy as np                                                                                                            # (29-JAN 2026)
l=[1,2,3]
a=np.array(l)
print(l)

[1, 2, 3]


In [3]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
a=np.array([[1,2,3],[1,2,4]])
print(a)

[[1 2 3]
 [1 2 4]]


In [ ]:
# SLICING 

#print(a[1])
#print(a[::])
#print(a[:2])
#print(a[1:])
#print(a[1::2])
#print(a[::2])
#print(a[:2:3])
#print(a[::-2])
print(a[-1:-3])
#print(a[-1:-3:-1])
print(a[-3:-1])

[]
[2 3]
