DAY-3 / 1-FEB 2026

In [2]:
# 1.random.rand()
import numpy as np
a=np.random.rand(3)
print(a)
b=np.random.rand(2,2)
print(b)
c=np.random.rand(2,3,4)
print(c)

[0.24075048 0.27682771 0.51363114]
[[0.21973467 0.558871  ]
 [0.77034617 0.87269624]]
[[[0.20217845 0.97172088 0.52008223 0.15503098]
  [0.80690102 0.73942619 0.03546965 0.99472283]
  [0.09555782 0.57104765 0.52278873 0.35872262]]

 [[0.26526718 0.79225793 0.17164666 0.55857519]
  [0.76809117 0.23801582 0.25028756 0.88932474]
  [0.25436897 0.81765313 0.65235112 0.31485884]]]


In [4]:
# 2.random.randint()
import numpy as np
a=np.random.randint(4)  # any one value between 0 to given value -1
print(a)
b=np.random.randint(1,10,5)   #any 5 value starting from desired value to given value -1
print(b)

1
[3 7 4 3 7]


In [5]:
# want +ve random numbers
a=np.random.randint(1,10,[2,3])
print(a)
b=np.random.randint(1,10,[2,2,2])
print(b)
c=np.random.randint((3,3,3))
print(c)

[[6 8 1]
 [7 3 6]]
[[[8 1]
  [9 1]]

 [[7 6]
  [6 5]]]
[0 0 2]


In [8]:
a=[1]
print(a)
b=np.random.randint(1,10,[2,3,4,5,1,6,7])
print(b)

[1]
[[[[[[[2 1 4 ... 9 8 8]
      [5 9 1 ... 2 6 8]
      [7 6 2 ... 4 2 4]
      [8 1 3 ... 1 6 1]
      [2 6 8 ... 7 3 3]
      [5 9 5 ... 8 3 9]]]


    [[[6 1 4 ... 1 3 3]
      [8 6 1 ... 6 3 5]
      [8 2 8 ... 1 9 1]
      [7 6 1 ... 8 1 6]
      [1 4 9 ... 6 7 1]
      [2 7 4 ... 6 4 3]]]


    [[[6 4 5 ... 8 9 9]
      [2 4 1 ... 7 6 1]
      [1 6 8 ... 9 7 1]
      [6 4 5 ... 7 5 3]
      [9 4 6 ... 1 2 2]
      [6 3 1 ... 8 1 1]]]


    [[[2 2 9 ... 6 7 5]
      [8 2 4 ... 2 1 9]
      [4 1 3 ... 7 7 6]
      [7 3 7 ... 3 9 3]
      [9 5 1 ... 3 5 2]
      [5 7 4 ... 1 7 3]]]


    [[[6 2 4 ... 8 2 3]
      [7 6 2 ... 2 6 4]
      [6 9 9 ... 4 4 8]
      [5 2 7 ... 7 6 2]
      [9 7 8 ... 6 6 6]
      [7 3 1 ... 3 7 5]]]]



   [[[[5 9 3 ... 9 3 9]
      [1 8 9 ... 2 6 7]
      [9 1 5 ... 3 8 9]
      [4 2 9 ... 3 5 9]
      [5 3 7 ... 8 7 5]
      [1 9 2 ... 9 3 2]]]


    [[[6 8 4 ... 9 6 4]
      [7 6 8 ... 8 7 3]
      [2 4 4 ... 7 1 9]
      [5 5 2 ... 2 4 3]
      [3 8

In [6]:
# randn()

b=np.random.randn(2,4) # value can be both -ve and +ve (-infinity to +infinity)
print(b)

[[-0.27916047 -0.12140987 -1.00704546 -0.27282525]
 [ 0.32328656  1.20790832  0.48329383  0.46730815]]


In [7]:
b=np.random.randn(2,4,3) # value can be both -ve and +ve (-infinity to +infinity)
print(b)

[[[ 0.17237775  0.09976705 -0.57937774]
  [ 1.37916692 -1.89570496  0.25726154]
  [ 0.29495622 -0.77668502  0.92959125]
  [ 0.73631386 -1.14690812 -0.35801831]]

 [[ 0.73170549  0.40088311 -1.02075626]
  [ 0.51978916  0.92149818  1.5002555 ]
  [ 0.41996263 -0.42410639 -1.53767393]
  [-0.00548086  0.00576091  0.2962414 ]]]
